const CONTENTFUL_TOKEN = import.meta.env.VITE_CONTENTFUL_TOKEN;
const CONTENTFUL_SPACE = import.meta.env.VITE_CONTENTFUL_SPACE;
const CONTENTFUL_ENTRY_ID = import.meta.env.VITE_CONTENTFUL_ENTRY_ID;

export { CONTENTFUL_TOKEN, CONTENTFUL_SPACE, CONTENTFUL_ENTRY_ID };